name: lanchonete_app
description: Um aplicativo de lanchonete para pedidos de lanches.
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/hamburguer_carne.jpg
    - assets/images/hamburguer_vegetariano.jpg
    - assets/images/hot_dog.jpg
    - assets/images/cheeseburger.jpg
    - assets/images/logo_lanchonete.png
  uses-material-design: true